---
title: "Impact Analysis"
date: "`r paste0('Last Updated: ', format(Sys.time(), '%d %B, %Y')) `"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include = F}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
knitr::opts_chunk$set(fig.align = 'center')

library(tidyverse)

# To Turn off Scientific Notation Use this.
options(scipen = 999)
```


# Executive Summary

__Prompt__

Imagine we ran an experiment to test the impact a Loop™ campaign has on sales. The experiment involved 42 stores in 3 groups:  

* _“Program test”_ These stores had the full Loop™ campaign as it would normally run, with a display of featured products and a tablet showing 2-3 films in a looping playlist  
* _“Film control”_ These stores had the full program but with the film from one brand (“Brewery A”) left out.   
* _“Baseline control”_ These stores did not have Loop™ campaigns or featured products on display.  

Assume you need to provide an analysis of this experiment under time constraints (in reality, we expect you to devote 2-4 hours to this audition project).

__Goal:__  
We want to know the impact the Loop™ campaign had on sales. By comparing the different groups we would like to learn a few different things:  

* Does the Loop campaign affect store sales (Program Test & Film Control vs Baseline)  
* What is the impact of the film of Brewery A on sales
 
 
__Assumptions:__ 
_(Note: this section would likely take a different shape as familarity with the data source increase/ relationship with the customer develops)_ 


* Would be interesting in future iterations, to get a more detailed view of what is being purchased. 
 
 
__Results:__
From the analysis we find that:

1. The program test and film control both show an increase in to sales velocity.


ANOVA to test for statistical significance


# Summary of Impact


# Digging into Results
